spring:
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  profiles:
    active: local
  application:
    name: cmc
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 300
      min-spare: 10

springdoc:
  api-docs:
    version: 'OPENAPI_3_0'
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-utl: true
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs

jwt:
  token:
    secret-key: eH0SIMQPTgoK7M1ZpyEbkOqmVXGby7JO
    access-token-expiration-time-in-seconds: 300 # 5분
    refresh-token-expiration-time-in-seconds: 77760000 # 90일