spring:
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  profiles:
    active: prd
  application:
    name: cmc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            trust: smtp.gmail.com

server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 300
      min-spare: 10

springdoc:
  api-docs:
    enabled: false
    version: 'OPENAPI_3_0'
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: false
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-utl: true
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs

jwt:
  token:
    secret-key: eH0SIMQPTgoK7M1ZpyEbkOqmVXGby7JO
    access-token-expiration-time-in-seconds: 300 # 5분
    refresh-token-expiration-time-in-seconds: 77760000 # 90일

openai:
  model: ${AI_MODEL}
  secret-key: ${AI_KEY}
  url:
    temp: https://api.openai.com/v1/chat/completions