spring:
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: 3600
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: always
  profiles:
    active: prd
  application:
    name: cmc
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enabled: true
            required: true
          ssl:
            trust: smtp.gmail.com

  data:
    redis:
      host: redis-server
      port: 6379
      # password: 1234
      database: 0 # 기본 데이터베이스
      timeout: 2000 # Redis 연결 타임아웃

      lettuce:
        pool:
          max-active: 8 # 최대 활성 커넥션 수
          max-idle: 8 # 최대 유휴 커넥션 수
          min-idle: 0 # 최소 유휴 커넥션 수
          max-wait: -1 # 커넥션 풀 대기시간 (무제한 대기)
  web:
    resources:
      add-mappings: false

server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 300
      min-spare: 10

springdoc:
  api-docs:
    enabled: true
    version: 'OPENAPI_3_0'
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-utl: true
    configUrl: /v3/api-docs/swagger-config
    url: /v3/api-docs

jwt:
  token:
    secret-key: ${JWT_SECRET_KEY}
    encryption-key: ${JWT_ENCRYPTION_KEY}
    access-token-expiration-time-in-seconds: 300 # 5분
    refresh-token-expiration-time-in-seconds: 7776000 # 90일

security:
  authorizationWhitelist:
    # Swagger
    - /
    - /index.html
    - /swagger-ui/**
    - /v3/api-docs/**
    - /livecoding
    - /livecodint/**
    # Join
    - /user/join
    - /user/join/google
    - /user/checkUserId
    - /user/checkUsername
    # Login
    - /user/tempLogin
    - /user/login
    - /user/login/google
    - /user/refresh
    - /user/tempRefresh
    - /user/findAccount

    # Comment
    - /selectComment
    - /selectCommentList
    # View
    - /updateReviewView
    - /updateBattleView
    # ReView
    - /selectReview
    - /selectReviewList
    # Battle
    - /selectBattle
    - /selectBattleList
    - /selectBattleVoteState

    # LiveCoding
    - /createLiveCoding
    - /selectLiveCoding
    - /deleteLiveCoding
    - /verifyLiveCoding
    - /selectLiveCodingSnippet
    - /updateLiveCodingSnippet

    # Like
    - /selectReviewLikeState


openai:
  model: ${AI_MODEL}
  secret-key: ${AI_KEY}
  url:
    temp: https://api.openai.com/v1/chat/completions

google:
  client-id: ${GOOGLE_CLIENT_ID}

# 도메인 수정 필요
domain: http://localhost:3000