openapi: 3.0.0
info:
  title: Battle api
  description: Cmc Battle api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: battle-controller
    description: Battle api controller

paths:
  /selectBattle:
    get:
      tags:
        - battle-controller
      summary: 배틀 단건 조회
      description: 배틀 단건 조회
      operationId: selectBattle
      parameters:
        - name: id
          in: query
          description: 배틀 id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/SelectBattleResDTO"
        '400':
          description: Invalid status value

  /selectBattleList:
    get:
      tags:
        - battle-controller
      summary: 배틀 리스트 조회
      description: 배틀 리스트 조회
      operationId: selectBattleList
      parameters:
        - name: condition
          in: query
          description: 조회 조건(0:최신순, 1:투표순, 2:로그인회원작성, 3:로그인회원투표참여)
          required: true
          schema:
            default: 0
            type: integer
        - name: page
          in: query
          description: 페이지 번호
          required: true
          schema:
            default: 0
            type: integer
        - name: size
          in: query
          description: 페이지 사이즈
          required: true
          schema:
            default: 10
            type: integer
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/SelectBattleListResDTO"
        '400':
          description: Invalid status value

  /createBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 생성"
      operationId: "createBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/CreateBattleReqDTO"
      responses:
        "200":
          description: "배틀 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/CreateBattleResDTO"
        "400":
          description: "배틀 생성 실패"

  /updateBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 수정"
      operationId: "updateBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/UpdateBattleReqDTO"
      responses:
        "200":
          description: "배틀 수정 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/UpdateBattleResDTO"
        "400":
          description: "배틀 수정 실패"

  /updateVoteBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 투표(기투표시 변경된 투표로 업데이트)"
      operationId: "updateVoteBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/UpdateVoteBattleReqDTO"
      responses:
        "200":
          description: "배틀 투표 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/UpdateVoteBattleResDTO"
        "400":
          description: "배틀 투표 실패"

  /deleteVoteBattle:
    post:
      tags:
        - battle-controller
      summary: "투표 삭제"
      operationId: "deleteVoteBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/DeleteVoteBattleReqDTO"
      responses:
        "200":
          description: "투표 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/DeleteVoteBattleResDTO"
        "400":
          description: "투표 삭제 실패"

  /deleteBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 삭제"
      operationId: "deleteBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/DeleteBattleReqDTO"
      responses:
        "200":
          description: "배틀 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/DeleteBattleResDTO"
        "400":
          description: "배틀 삭제 실패"