openapi: 3.0.0
info:
  title: Battle api
  description: Cmc Battle api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: battle-controller
    description: Battle api controller

paths:
  /selectBattle:
    get:
      tags:
        - battle-controller
      summary: 배틀 단건 조회
      description: 배틀 단건 조회
      operationId: selectBattle
      parameters:
        - name: id
          in: query
          description: 배틀 id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/SelectBattleResDTO"
        '400':
          description: Invalid status value

  /createBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 생성"
      operationId: "createBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/CreateBattleReqDTO"
      responses:
        "200":
          description: "배틀 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/CreateBattleResDTO"
        "400":
          description: "배틀 생성 실패"

  /deleteBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 삭제"
      operationId: "deleteBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/DeleteBattleReqDTO"
      responses:
        "200":
          description: "배틀 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/DeleteBattleResDTO"
        "400":
          description: "배틀 삭제 실패"