openapi: 3.0.0
info:
  title: Battle api
  description: Cmc Battle api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: battle-controller
    description: Battle api controller

paths:
  /createBattle:
    post:
      tags:
        - battle-controller
      summary: "배틀 생성"
      operationId: "createBattle"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/CreateBattleReqDTO"
      responses:
        "200":
          description: "배틀 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/battle/BattleDTO.yaml#/components/schemas/CreateBattleResDTO"
        "400":
          description: "배틀 생성 실패"