openapi: 3.0.0
info:
  title: Cmc api
  version: 1.0.0
  description: Cmc api

servers:
  - url: http://localhost:8080

tags:
  - name: cmc-controller
    description: Cmc api controller

paths:
  /getStashDetail:
    get:
      tags:
        - cmc-controller
      summary: API_CMC_0001, Cmc 상세 조회
      description: Cmc 상세 조회
      operationId: getCmcDetail
      parameters:
        - name: cmcId
          in: query
          description: cmc 아이디
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회성공
          content:
            application/json:
              schema:
                $ref: './dto/CmcDTO.yaml#/components/schemas/CreateCmcInDTO'
        '400':
          description: Invalid status value