openapi: 3.0.0
info:
  title: Comment api
  description: Cmc Comment api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: comment-controller
    description: Comment api controller

paths:
  /selectComment:
    get:
      tags:
        - comment-controller
      summary: 댓글 단건 조회
      description: 댓글 단건 조회
      operationId: selectComment
      parameters:
        - name: id
          in: query
          description: 댓글 id
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/SelectCommentResDTO"
        '400':
          description: Invalid status value

  /selectCommentList:
    get:
      tags:
        - comment-controller
      summary: 댓글 다건 조회
      description: 댓글 다건 조회
      operationId: selectCommentList
      parameters:
        - name: targetId
          in: query
          description: 타겟 id
          required: true
          schema:
            type: integer
            format: int64
        - name: commentTarget
          in: query
          description: 타겟 구분
          required: true
          schema:
            type: integer
        - name: page
          in: query
          description: 페이지 번호
          required: true
          schema:
            default: 0
            type: integer
        - name: size
          in: query
          description: 페이지 사이즈
          required: true
          schema:
            default: 10
            type: integer
      responses:
        '200':
          description: 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/SelectCommentListResDTO"
        '400':
          description: Invalid status value

  /createComment:
    post:
      tags:
        - comment-controller
      summary: "댓글 생성"
      operationId: "createComment"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/CreateCommentReqDTO"
      responses:
        "200":
          description: "댓글 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/CreateCommentResDTO"
        "400":
          description: "댓글 생성 실패"

  /deleteComment:
    post:
      tags:
        - comment-controller
      summary: "댓글 삭제"
      operationId: "deleteComment"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/DeleteCommentReqDTO"
      responses:
        "200":
          description: "댓글 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/DeleteCommentResDTO"
        "400":
          description: "댓글 삭제 실패"

  /updateComment:
    post:
      tags:
        - comment-controller
      summary: "댓글 수정"
      operationId: "updateComment"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/UpdateCommentReqDTO"
      responses:
        "200":
          description: "댓글 수정 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/comment/CommentDTO.yaml#/components/schemas/UpdateCommentResDTO"
        "400":
          description: "댓글 수정 실패"
