openapi: 3.0.0
info:
  title: Guide api
  version: 1.0.0
  description: Cmc api

servers:
  - url: http://localhost:8080

tags:
  - name: guide-controller
    description: Guide api controller

paths:
  /getGuideQuery:
    get:
      tags:
        - guide-controller
      summary: "get 방식 api(쿼리 파라미터), id 기반 조회 예시"
      operationId: "getGuideQuery"
      parameters:
        - name: id
          in: query
          required: false
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "get 방식 api(쿼리 파라미터) 정상 반환 - 간략한 설명 추가"
          content:
            application/json:
              schema:
                $ref: "./dto/GuideDTO.yaml#/components/schemas/GetGuideQueryResponse"
        "400":
          description: "get 방식 api(쿼리 파라미터) 400 에러 반환"
        "401":
          description: "get 방식 api(쿼리 파라미터) 401 에러 반환"

  /getGuideDTO:
    get:
      tags:
        - guide-controller
      summary: "get 방식 api(DTO 파라미터), id 기반 조회 예시"
      operationId: "getGuideDTO"
      parameters:
        - name: guideDTO
          in: query
          required: true
          schema:
            $ref: "./dto/GuideDTO.yaml#/components/schemas/GuideDTORequest"
      responses:
        "200":
          description: "get 방식 api(DTO 파라미터) 정상 반환 - 간략한 설명 추가"
          content:
            application/json:
              schema:
                $ref: "./dto/GuideDTO.yaml#/components/schemas/GetGuideDTOResponse"

  /postGuideCreate:
    post:
      tags:
        - guide-controller
      summary: "post 방식 api, 데이터 생성 예시"
      operationId: "postGuideCreate"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/GuideDTO.yaml#/components/schemas/PostGuideCreateRequest"
      responses:
        "201":
          description: "post 방식 api 정상 반환 - 간략한 설명 추가"
          content:
            application/json:
              schema:
                $ref: "./dto/GuideDTO.yaml#/components/schemas/PostGuideCreateResponse"

  /postGuideUpdate:
    post:
      tags:
        - guide-controller
      summary: "post 방식 api, 데이터 수정 예시"
      operationId: "postGuideUpdate"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/GuideDTO.yaml#/components/schemas/PostGuideUpdateRequest"
      responses:
        "201":
          description: "post 방식 api 정상 반환 - 간략한 설명 추가"
          content:
            application/json:
              schema:
                $ref: "./dto/GuideDTO.yaml#/components/schemas/PostGuideUpdateResponse"

  /postGuideDelete:
    post:
      tags:
        - guide-controller
      summary: "post 방식 api, 데이터 삭제 예시"
      operationId: "postGuideDelete"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/GuideDTO.yaml#/components/schemas/PostGuideDeleteRequest"
      responses:
        "201":
          description: "post 방식 api 정상 반환 - 간략한 설명 추가"
          content:
            application/json:
              schema:
                $ref: "./dto/GuideDTO.yaml#/components/schemas/PostGuideDeleteResponse"

components:
  schemas:
    Guide:
      $ref: './entity/GuideEntity.yaml#/components/schemas/Guide'