openapi: 3.0.0
info:
  title: LiveCoding API
  description: CMC LiveCoding API
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: live-coding-controller
    description: LiveCoding API controller

paths:
  /createLiveCoding:
    post:
      tags:
        - live-coding-controller
      summary: "라이브 코딩 방 생성"
      operationId: "createLiveCoding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/CreateLiveCodingReqDTO"
      responses:
        "200":
          description: "라이브 코딩 방 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/CreateLiveCodingResDTO"
        "400":
          description: "라이브 코딩 방 생성 실패"

  /deleteLiveCoding:
    post:
      tags:
        - live-coding-controller
      summary: "라이브 코딩 방 삭제"
      operationId: "deleteLiveCoding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/DeleteLiveCodingReqDTO"
      responses:
        "200":
          description: "라이브 코딩 방 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/DeleteLiveCodingResDTO"
        "400":
          description: "라이브 코딩 방 삭제 실패"

  /updateLiveCoding:
    post:
      tags:
        - live-coding-controller
      summary: "라이브 코딩 방 정보 업데이트"
      operationId: "updateLiveCoding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/UpdateLiveCodingReqDTO"
      responses:
        "200":
          description: "라이브 코딩 방 정보 업데이트 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/UpdateLiveCodingResDTO"
        "400":
          description: "라이브 코딩 방 정보 업데이트 실패"

  /selectLiveCoding:
    get:
      summary: "라이브 코딩 방 조회"
      tags:
        - live-coding-controller
      operationId: "selectLiveCoding"
      description: "주어진 roomId에 해당하는 라이브 코딩 방을 조회합니다."
      parameters:
        - name: roomId
          in: query
          description: "라이브 코딩 방 ID"
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: "라이브 코딩 방 정보 조회 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/SelectLiveCodingResDTO"
        "400":
          description: "잘못된 요청"

  /inviteLiveCoding:
    post:
      tags:
        - live-coding-controller
      summary: "라이브 코딩 방 초대 링크 생성"
      operationId: "inviteLiveCoding"
      description: "roomId(UUID)를 기반으로 JWT를 포함한 초대 링크를 생성."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/InviteLiveCodingReqDTO"
      responses:
        "200":
          description: "초대 링크 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/InviteLiveCodingResDTO"
        "400":
          description: "잘못된 요청 (roomId 없음)"

  /existLiveCoding:
    get:
      tags:
        - live-coding-controller
      summary: "라이브 코딩 방 생성여부 조회"
      operationId: "existLiveCoding"
      description: "hostId 기준으로 방 생성됬는지 확인."
      parameters:
        - name: hostId
          in: query
          description: "host ID"
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: "초대 링크 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/ExistLiveCodingResDTO"
        "400":
          description: "잘못된 요청"


  /verifyLiveCoding:
    post:
      tags:
        - live-coding-controller
      summary: "라이브 코딩 토큰 검증"
      operationId: "verifyLiveCoding"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/verifyLiveCodingReqDTO"
      responses:
        "200":
          description: "라이브 코딩 토큰 검증 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/lcd/LiveCodingDTO.yaml#/components/schemas/verifyLiveCodingResDTO"
        "400":
          description: "라이브 코딩 토큰 검증 실패"
