openapi: 3.0.0
info:
  title: Notice api
  description: Cmc Notice api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: notice-controller
    description: Notice api controller

paths:

  /selectPageNotice:
    get:
      tags:
        - notice-controller
      summary: 알림 리스트 조회(페이징)
      description: 페이징된 알림 리스트를 조회합니다.
      operationId: selectPageNotice
      parameters:
        - name: page
          in: query
          description: 요청할 페이지 번호 (0부터 시작)
          required: true
          schema:
            type: integer
            format: int32
            example: 0
        - name: size
          in: query
          description: 한 페이지 당 개수
          required: true
          schema:
            type: integer
            format: int32
            example: 10
      responses:
        '200':
          description: 알림 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/notice/NoticeDTO.yaml#/components/schemas/SelectNoticeListDTO"
        '400':
          description: 잘못된 요청입니다.

  /deleteNotie:
    post:
      tags:
        - notice-controller
      summary: "알림 삭제"
      operationId: "deleteNotice"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/notice/NoticeDTO.yaml#/components/schemas/DeleteNoticeReqDTO"
      responses:
        "200":
          description: "댓글 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/notice/NoticeDTO.yaml#/components/schemas/DeleteNoticeResDTO"
        "400":
          description: "댓글 삭제 실패"

  /deleteNoticeAll:
    post:
      tags:
        - notice-controller
      summary: "알림 전체 삭제"
      operationId: "deleteNoticeAll"
      responses:
        "200":
          description: "댓글 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/notice/NoticeDTO.yaml#/components/schemas/DeleteNoticeAllResDTO"
        "400":
          description: "댓글 삭제 실패"
