openapi: 3.0.0
info:
  title: Notice api
  description: Cmc Notice api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: notice-controller
    description: Notice api controller

paths:
  /selectNotice:
    get:
      tags:
        - notice-controller
      summary: 알림 리스트 조회
      description: 알림 리스트 조회
      operationId: selectNotice
      parameters:
        - name: userNum
          in: query
          description: 유저ID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 알림 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/notice/NoticeDTO.yaml#/components/schemas/SelectNoticeListDTO"
        '400':
          description: Invalid status value