openapi: 3.0.0
info:
  title: Redis API
  description: Cmc Redis api
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: redis-controller
    description: Redis api controller

paths:
  /saveRedis:
    post:
      summary: Redis에 항목 저장
      operationId: saveRedis
      tags:
        - redis-controller  # 태그 추가
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/SaveRedisReqDTO"
      responses:
        '201':
          description: 레디스 저장 성공
          content:
            application/json:
              schema:
                $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/SaveRedisResDTO"
        '400':
          description: 레디스 저장 실패

  /selectRedis:
    get:
      summary: 특정 키로 Redis 항목 조회
      operationId: selectRedis
      tags:
        - redis-controller  # 태그 추가
      parameters:
        - name: key
          in: query
          required: true
          description: Redis 항목의 키
          schema:
            type: string
      responses:
        '200':
          description: 레디스 성공 실패
          content:
            application/json:
              schema:
                $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/SelectRedisResDTO"
        '404':
          description: 레디스 조회 실패

  /deleteRedis:
    post:
      summary: Redis 항목 삭제
      operationId: deleteRedis
      tags:
        - redis-controller  # 태그 추가
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/DeleteRedisReqDTO"
      responses:
        '200':
          description: 레디스 삭제 성공
        '404':
          description: 레디스 삭제 실패

  /saveHash:
    post:
      summary: Redis 해시에 항목 저장
      operationId: saveHash
      tags:
        - redis-controller  # 태그 추가
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/SaveHashReqDTO"
      responses:
        '201':
          description: 레디스 해시 저장 성공
          content:
            application/json:
              schema:
                $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/SaveHashResDTO"
        '400':
          description: 레디스 해시 저장 실패


  /selectHash:
    get:
      summary: Redis 해시 조회
      operationId: selectHash
      tags:
        - redis-controller  # 태그 추가
      parameters:
        - name: key
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 레디스 해시 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/redis/RedisDTO.yaml#/components/schemas/SelectHashResDTO"
        '404':
          description: 레디스 해시 조회 실패
