openapi: 3.0.0
info:
  title: Review API
  description: Review 관련 API
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: review-controller
    description: Review API Controller

paths:
  /selectReview:
    get:
      tags:
        - review-controller
      summary: 리뷰 단건 조회
      description: 리뷰 단건 조회
      operationId: selectReview
      parameters:
        - name: review_id
          in: query
          description: 리뷰 ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 리뷰 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/SelectReviewResDTO"
        '400':
          description: Invalid status value
  /selectReviewList:
    get:
      tags:
        - review-controller
      summary: 리뷰 리스트 조회
      description: 리뷰 리스트 조회
      operationId: selectReviewList
      parameters:
        - name: condition
          in: query
          description: 조회 조건(0:최신순, 1:인기순, 2:로그인회원작성, 3:로그인회원답변, 4:로그인회원좋아요)
          required: true
          schema:
            default: 0
            type: integer
        - name: pageNumber
          in: query
          description: 페이지 번호 (0부터 시작)
          required: false
          schema:
            type: integer
            default: 0
        - name: pageSize
          in: query
          description: 한 페이지당 리뷰 개수
          required: false
          schema:
            type: integer
            default: 10
      responses:
        '200':
          description: 리뷰 리스트 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/SelectReviewListResDTO"
        '400':
          description: Invalid status value
  /createReview:
    post:
      tags:
        - review-controller
      summary: 리뷰 생성
      description: 리뷰 생성
      operationId: createReview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/CreateReviewReqDTO"
      responses:
        "200":
          description: "리뷰 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/CreateReviewResDTO"
        "400":
          description: "리뷰 생성 실패"
  /deleteReview:
    post:
      tags:
        - review-controller
      summary: "리뷰 삭제"
      operationId: "deleteReview"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/DeleteReviewReqDTO"
      responses:
        "200":
          description: "리뷰 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/DeleteReviewResDTO"
        "400":
          description: "리뷰 삭제 실패"

  /updateReview:
    post:
      tags:
        - review-controller
      summary: "리뷰 수정"
      operationId: "updateReview"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/UpdateReviewReqDTO"
      responses:
        "200":
          description: "리뷰 수정 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/UpdateReviewResDTO"
        "400":
          description: "리뷰 수정 실패"