openapi: 3.0.0
info:
  title: Review API
  description: Review 관련 API
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: review-controller
    description: Review API Controller

paths:
  /selectReview:
    get:
      tags:
        - review-controller
      summary: 리뷰 리스트 조회
      description: 리뷰 리스트 조회
      operationId: selectReview
      parameters:
        - name: userNum
          in: query
          description: 유저 ID
          required: true
          schema:
            type: string
#        - name: page // 페이징 작업중
#          in: query
#          description: 페이지 번호 (0부터 시작)
#          required: false
#          schema:
#            type: integer
#            default: 0
#        - name: size
#          in: query
#          description: 한 페이지당 리뷰 개수
#          required: false
#          schema:
#            type: integer
#            default: 10
      responses:
        '200':
          description: 리뷰 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/SelectReviewResDTO"
        '400':
          description: Invalid status value