openapi: 3.0.0
info:
  title: Review API
  description: Review 관련 API
  version: 1.0.0

servers:
  - url: http://localhost:8080

tags:
  - name: review-controller
    description: Review API Controller

paths:
  /selectReview:
    get:
      tags:
        - review-controller
      summary: 리뷰 단건 조회
      description: 리뷰 단건 조회
      operationId: selectReview
      parameters:
        - name: review_id
          in: query
          description: 리뷰 ID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 리뷰 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/SelectReviewResDTO"
        '400':
          description: Invalid status value
  /selectReviewList:
    get:
      tags:
        - review-controller
      summary: 리뷰 리스트 조회
      description: 리뷰 리스트 조회
      operationId: selectReviewList
      parameters:
        - name: pageNumber
          in: query
          description: 페이지 번호 (0부터 시작)
          required: false
          schema:
            type: integer
            default: 0
        - name: pageSize
          in: query
          description: 한 페이지당 리뷰 개수
          required: false
          schema:
            type: integer
            default: 10
        - name: sort
          in: query
          description:
            정렬 기준 (createdAt, likes)
          required: false
          schema:
            type: string
            enum: [createdAt, updatedAt, title]
            default: "createdAt"
        - name: order
          in: query
          description: 정렬 순서 (오름/ 내림)
          required: false
          schema:
            type: string
            enum: [ asc, desc ]
            default: "desc"
        - name: keyword
          in: query
          description: 검색 키워드
          required: false
          schema:
            type: string
#        - name: filterType
#          in: query
#          description: 사용자 관련 필터 타입 (작성/답변/좋아요한 리뷰)
#          required: false
#          schema:
#            type: string
#            enum: [ written, replied, liked ]
#        - name: userNum
#          in: query
#          description: 사용자 식별자
#          required: false
#          schema:
#            type: integer
      responses:
        '200':
          description: 리뷰 리스트 조회 성공
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/SelectReviewListResDTO"
        '400':
          description: Invalid status value
  /createReview:
    post:
      tags:
        - review-controller
      summary: 리뷰 생성
      description: 리뷰 생성
      operationId: createReview
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/CreateReviewReqDTO"
      responses:
        "200":
          description: "리뷰 생성 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/CreateReviewResDTO"
        "400":
          description: "리뷰 생성 실패"
  /deleteReview:
    post:
      tags:
        - review-controller
      summary: "리뷰 삭제"
      operationId: "deleteReview"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/DeleteReviewReqDTO"
      responses:
        "200":
          description: "리뷰 삭제 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/DeleteReviewResDTO"
        "400":
          description: "리뷰 삭제 실패"

  /updateReview:
    post:
      tags:
        - review-controller
      summary: "리뷰 수정"
      operationId: "updateReview"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/UpdateReviewReqDTO"
      responses:
        "200":
          description: "리뷰 수정 성공"
          content:
            application/json:
              schema:
                $ref: "./dto/review/ReviewDTO.yaml#/components/schemas/UpdateReviewResDTO"
        "400":
          description: "리뷰 수정 실패"